---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '^2.0.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami-sealed-secrets
  values:
    additionalNamespaces:
      - metrics
