---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.23.6
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-controller=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 81
        protocol: TCP
      - containerPort: 443
        hostPort: 444
        protocol: TCP
      - containerPort: 6969
        hostPort: 6970
        protocol: TCP
      - containerPort: 8080
        hostPort: 8081
        protocol: TCP
  - role: worker
    image: kindest/node:v1.23.6
  - role: worker
    image: kindest/node:v1.23.6
  - role: worker
    image: kindest/node:v1.23.6
