---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo
spec:
  interval: 5m
  chart:
    spec:
      chart: echo-server
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: ealenn-charts
        namespace: echo
      interval: 5m
  releaseName: echo-server
  # targetNamespace: echo
  install:
    # createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
