---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: metrics
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`grafana.localhost`)
      kind: Rule
      middlewares:
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
          scheme: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: metrics
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`prometheus.localhost`)
      kind: Rule
      middlewares:
      services:
        - name: prometheus-kube-prometheus-prometheus
          port: 9090
          scheme: http
