---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sealed-secrets
  - ../base/kube-prometheus-stack
  - ../base/echo-server
patches:
  - path: kube-prometheus-stack/release-patch.yaml
    target:
      kind: HelmRelease
  - path: kube-prometheus-stack/ingress-patch.yaml
    target:
      kind: IngressRoute
