---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
  - ../base/sealed-secrets
  - ../base/kube-prometheus-stack
patches:
  - path: kube-prometheus-stack-values.yaml
    target:
      kind: HelmRelease
